# Pipeline Logstash minimal – réception logs TCP (JSON) et envoi vers Elasticsearch

input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service" => "microcrm" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
}
